### PR TITLE
I#77: Same user cannot be added to same team

### PR DESCRIPTION
**Pull request by shreyansjain**
#77

### CODE REVIEW

**Comment by anmolg** [comment]
I would propose different approach:
1) Create a unique constraint for team_id, user_id
2) If pg_error, display error code

**Comment by shreyansjain** [comment]
Why rely on PG error? We don't need to show any DB logs/stack trace to the client side

**Comment by shreyansjain** [comment]
@anmolg added the unique constraint db script. Implication is to delete the rows in user_team that are duplicated

**Comment by anmolg** [comment]
should be unique right now. Just deleted everything this morning and maintained that constraint mentally

**Pull request merged**
